package io.github.remmerw.thor.dom

enum class ElementType {
    A, META, HEAD, B, TBODY, CAPTION, SMALL,
    LINK, ANCHOR, TABLE, TD,
    TH, TR, STYLE, IMG, SCRIPT, SPAN, Q,
    BLOCKQUOTE, P, PRE, BODY, DL, DIV, FORM, INPUT,
    BUTTON, TEXTAREA, SELECT, OPTION, FRAMESET, FRAME,
    IFRAME, UL, OL, LI, HR, BR, OBJECT, APPLET, EMBED, FONT,
    BASEFONT, H1, H2, H3, H4, H5, H6, CANVAS, HTML, TITLE, BASE,
    UNKNOWN, CENTER, BIG
}